version: '3.8'

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/backend:${TAG}
    networks:
      - backend-net
      - traefik-public
    env_file:
      - .env
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        
        # Service
        - "traefik.http.services.backend-${ENV}.loadbalancer.server.port=5000"
        
        # HTTPS Router
        - "traefik.http.routers.backend-${ENV}-secure.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.backend-${ENV}-secure.entrypoints=websecure"
        - "traefik.http.routers.backend-${ENV}-secure.tls=true"
        - "traefik.http.routers.backend-${ENV}-secure.tls.certresolver=leresolver"
        - "traefik.http.routers.backend-${ENV}-secure.service=backend-${ENV}"
        
        # HTTP Router avec redirection
        - "traefik.http.routers.backend-${ENV}-http.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.backend-${ENV}-http.entrypoints=web"
        - "traefik.http.routers.backend-${ENV}-http.middlewares=redirect-to-https"
        
        # Middleware redirect
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

networks:
  backend-net:
    driver: overlay
  traefik-public:
    external: true